import { Food } from "./app/shared/models/Food";

export const sample_foodData: Food[] = [
    {
      id: "1",
      name: "Margherita Pizza",
      price: 9.99,
      tags: ["Italian", "Pizza"],
      favorite: true,
      stars: 4.8,
      imageurl: "assets/margherita-pizza.jpg",
      origins: ["Italy"],
      cooktime: "20 minutes",
    },
    {
      id: "2",
      name: "Sushi Roll",
      price: 15.99,
      tags: ["Japanese", "Sushi"],
      favorite: false,
      stars: 4.5,
      imageurl: "assets/sushi-roll.jpg",
      origins: ["Japan"],
      cooktime: "15 minutes",
    },
    {
      id: "3",
      name: "Classic Burger",
      price: 8.49,
      tags: ["American", "Burger"],
      favorite: true,
      stars: 4.2,
      imageurl: "assets/classic-burger.jpg",
      origins: ["United States"],
      cooktime: "25 minutes",
    },
    {
      id: "4",
      name: "Pad Thai",
      price: 11.99,
      tags: ["Thai", "Noodles"],
      favorite: false,
      stars: 4.6,
      imageurl: "assets/pad-thai.jpg",
      origins: ["Thailand"],
      cooktime: "30 minutes",
    },
    {
      id: "5",
      name: "Caesar Salad",
      price: 7.99,
      tags: ["Salad"],
      favorite: true,
      stars: 4.0,
      imageurl: "assets/caesar-salad.jpg",
      origins: ["United States"],
      cooktime: "15 minutes",
    },
    {
      id: "6",
      name: "Tacos",
      price: 10.49,
      tags: ["Mexican"],
      favorite: false,
      stars: 4.4,
      imageurl: "assets/tacos.jpg",
      origins: ["Mexico"],
      cooktime: "20 minutes",
    },
    {
      id: "7",
      name: "Chocolate Cake",
      price: 12.99,
      tags: ["Dessert", "Cake"],
      favorite: true,
      stars: 4.7,
      imageurl: "assets/chocolate-cake.jpg",
      origins: ["Unknown"],
      cooktime: "40 minutes",
    },
    {
      id: "8",
      name: "Miso Soup",
      price: 6.99,
      tags: ["Japanese", "Soup"],
      favorite: false,
      stars: 4.1,
      imageurl: "assets/miso-soup.jpg",
      origins: ["Japan"],
      cooktime: "15 minutes",
    },
    {
      id: "9",
      name: "Chicken Caesar Wrap",
      price: 9.49,
      tags: ["Wrap", "Chicken"],
      favorite: true,
      stars: 4.3,
      imageurl: "assets/chicken-caesar-wrap.jpg",
      origins: ["United States"],
      cooktime: "20 minutes",
    },
    {
      id: "10",
      name: "Hawaiian Poke Bowl",
      price: 13.99,
      tags: ["Hawaiian", "Poke", "Bowl"],
      favorite: false,
      stars: 4.6,
      imageurl: "assets/hawaiian-poke-bowl.jpg",
      origins: ["Hawaii"],
      cooktime: "15 minutes",
    },
];

  